### ISSUE TITLE
Toast component

### ISSUE THREAD

**Issue by Petrovski** [cynerge-consulting/smokejumpers#17]
A toast component may need to be created to replace situations in the app where an action that was successful is currently using a modal. A toast component is a better use case for these and should maybe be applied here. Specs below:

- [x] Usable app wide
- [x] Has different toast types such as `success`, `warning`, `info,` etc. for different use cases
- [x] Styled nicely with some animation
- [x] Will persist through route changes
- [x] Has an "X" in the top right to close it, as well as an auto close after a set amount of time

**Comment by Petrovski** [comment]
> @Petrovski if you have bandwidth do you wanna [spec](https://github.com/cynerge-consulting/conventions/wiki/Development-Process#specifications) this one out and get started on it?

Updated specs, please review when you get a chance

**Comment by briandavidson** [comment]
yup, this captures everything we need for a first release of the component, specs approved!
