### ISSUE TITLE
Navbar/sidenav needs refactoring to account for FS header

### ISSUE THREAD

**Issue by Petrovski** [cynerge-consulting/smokejumpers#39]
Trying to implement the FS header into the app isn't working well (see photo below). We may need to refactor how the navbar and sidenav sit on the page to account for this.

![Capture](https://user-images.githubusercontent.com/40745333/114624984-95075f00-9c7f-11eb-9ba4-0215c223533f.PNG)

**Comment by briandavidson** [comment]
@Petrovski this ticket is redundant with https://github.com/cynerge-consulting/smokejumpers/issues/19. Part of the requirements for that ticket include not causing any regression issues, which is what this is. Let's close this out and instead make sure the original issue gets done correctly please.

cc @mtlaney
