### ISSUE TITLE
replicate auth.guard functionality

### ISSUE THREAD

**Issue by briandavidson** [cynerge-consulting/smokejumpers#6]
do we need to restrict access to certain routes? if so, we need to implement something like auth guards.

**specs**
TBD

**Comment by briandavidson** [comment]
@Petrovski I think this is good to go based on our brief testing on the dev server but there's no list specs, and not a lot to go on for you to PR / review this. I feel good calling this done for now unless there's something I missed, what do you think?

**Comment by Petrovski** [comment]
@briandavidson I think we are good on this one, it seemed to be working okay. If we need to change it, we can just open a new issue that will explain what needs to be changed.

**Comment by briandavidson** [comment]
> @briandavidson I think we are good on this one, it seemed to be working okay. If we need to change it, we can just open a new issue that will explain what needs to be changed.

💥
